apiVersion: v1
kind: Service
metadata: {name: scam2market-api}
spec:
  selector: {app.kubernetes.io/name: scam2market, app.kubernetes.io/component: api}
  ports: [{name: http, port: {{ .Values.service.port }}, targetPort: http}]
