const state={alerts:[],campaigns:[],severity:"ALL",selected:null};
const el=id=>document.getElementById(id);
function headers(write=false){const token=sessionStorage.getItem("s2m_token");const h={};if(token)h.Authorization=`Bearer ${token}`;else{h["X-Dev-Roles"]=write?"ANALYST":"VIEWER";h["X-Actor-ID"]="analyst-dashboard"}if(write)h["Content-Type"]="application/json";return h}
async function api(path,options={}){const response=await fetch(`/api/v1${path}`,{...options,headers:{...headers(options.method&&options.method!=="GET"),...(options.headers||{})}});if(response.status===401){el("auth-panel").hidden=false;throw new Error("Authentication required")}if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);return response.json()}
const safe=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const ago=value=>{if(!value)return "Unknown";const seconds=Math.max(0,(Date.now()-new Date(value).getTime())/1000);if(seconds<60)return `${Math.floor(seconds)}s ago`;if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;return `${Math.floor(seconds/3600)}h ago`};
function filteredAlerts(){const query=el("search").value.toLowerCase();return state.alerts.filter(a=>(state.severity==="ALL"||a.severity===state.severity)&&`${a.alert_type} ${a.campaign_id}`.toLowerCase().includes(query))}
function renderAlerts(){const rows=filteredAlerts();el("empty-alerts").hidden=rows.length>0;el("alert-rows").innerHTML=rows.map(a=>`<tr data-id="${safe(a.alert_id)}" class="${state.selected===a.alert_id?"selected":""}"><td><span class="pill ${safe(a.severity)}">${safe(a.severity)}</span></td><td>${safe(a.alert_type.replaceAll("_"," "))}</td><td>${safe(a.campaign_id.slice(0,8))}</td><td>${safe(a.occurrence_count)}</td><td>${safe(ago(a.last_triggered_at))}</td></tr>`).join("");document.querySelectorAll("#alert-rows tr").forEach(row=>row.onclick=()=>selectAlert(row.dataset.id))}
function selectAlert(id){state.selected=id;const a=state.alerts.find(item=>item.alert_id===id);if(!a)return;el("alert-detail").innerHTML=`<h2>${safe(a.alert_type.replaceAll("_"," "))}</h2><span class="pill ${safe(a.severity)}">${safe(a.severity)}</span><dl><dt>Alert ID</dt><dd>${safe(a.alert_id)}</dd><dt>Campaign</dt><dd>${safe(a.campaign_id)}</dd><dt>Status</dt><dd>${safe(a.status)}</dd><dt>Last triggered</dt><dd>${safe(new Date(a.last_triggered_at).toLocaleString())}</dd></dl><button id="ack" class="primary">Acknowledge</button>`;el("ack").onclick=()=>acknowledge(a);renderAlerts()}
async function acknowledge(alert){await api(`/alerts/${alert.alert_id}/acknowledge`,{method:"POST",body:JSON.stringify({note:"Acknowledged from analyst dashboard"})});state.alerts=state.alerts.filter(item=>item.alert_id!==alert.alert_id);state.selected=null;el("alert-detail").innerHTML="<h2>Alert acknowledged</h2><p>The action is recorded in the audit trail.</p>";render()}
function renderCampaigns(){el("campaign-grid").innerHTML=state.campaigns.map(c=>`<article class="campaign"><header><strong>${safe(c.asset_id)}</strong><span class="stage">${safe(c.stage.replaceAll("_"," "))}</span></header><dl><div><dt>Max severity</dt><dd>${safe(c.max_severity)}</dd></div><div><dt>Confidence</dt><dd>${safe(Math.round(c.stage_confidence*100))}%</dd></div><div><dt>Status</dt><dd>${safe(c.status)}</dd></div><div><dt>Last evidence</dt><dd>${safe(ago(c.last_evidence_at))}</dd></div></dl></article>`).join("")||'<div class="empty">No open campaigns.</div>'}
function render(){el("active-count").textContent=state.alerts.length;el("critical-count").textContent=state.alerts.filter(a=>a.severity==="CRITICAL").length;el("campaign-count").textContent=state.campaigns.filter(c=>c.status!=="CLOSED").length;renderAlerts();renderCampaigns()}
async function refresh(){try{const [alerts,campaigns,ready,checkpoints]=await Promise.all([api("/alerts?limit=200"),api("/campaigns?limit=200"),api("/ready"),api("/operations/worker-checkpoints")]);state.alerts=alerts;state.campaigns=campaigns;el("pipeline-state").textContent=ready.status||"Ready";el("readiness").innerHTML=Object.entries(ready.checks||ready).map(([k,v])=>`<dt>${safe(k.replaceAll("_"," "))}</dt><dd>${safe(typeof v==="object"?(v.status||JSON.stringify(v)):v)}</dd>`).join("");el("checkpoints").innerHTML=checkpoints.map(c=>`<div class="checkpoint"><span>${safe(c.consumer_group)} / ${safe(c.topic)}:${safe(c.partition)}</span><span>Offset ${safe(c.last_durable_offset)}</span><span>${safe(ago(c.updated_at))}</span></div>`).join("")||'<p>No durable checkpoints recorded.</p>';el("connection").textContent="Live · 15s";el("connection").classList.add("online");el("last-updated").textContent=`Updated ${new Date().toLocaleTimeString()}`;render()}catch(error){el("connection").textContent="Disconnected";el("connection").classList.remove("online");console.error(error)}}
document.querySelectorAll(".nav-item").forEach(button=>button.onclick=()=>{document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));button.classList.add("active");const target=button.dataset.view==="overview"?"alerts":button.dataset.view;document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));el(`${target}-view`).classList.add("active")});
document.querySelectorAll("[data-severity]").forEach(button=>button.onclick=()=>{state.severity=button.dataset.severity;document.querySelectorAll("[data-severity]").forEach(x=>x.classList.remove("selected"));button.classList.add("selected");renderAlerts()});el("search").oninput=renderAlerts;el("refresh").onclick=refresh;el("auth-form").onsubmit=event=>{event.preventDefault();sessionStorage.setItem("s2m_token",el("token").value);el("auth-panel").hidden=true;refresh()};refresh();setInterval(refresh,15000);
